const plugin = require("tailwindcss/plugin");
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./dev/**/*.js", "./views/**/*.php", "./dev/**/*.css"],
    theme: {
        screens: {
            "min-2xl": { min: "1681px" },
            "min-xl": { min: "1441px" },
            "min-lg": { min: "1281px" },
            "min-md": { min: "1025px" },
            "min-sm": { min: "769px" },
            "min-xs": { min: "481px" },
            "2xl": { max: "1680px" },
            xl: { max: "1440px" },
            lg: { max: "1280px" },
            md: { max: "1024px" },
            sm: { max: "768px" },
            xsm: { max: "624px" },
            xs: { max: "480px" },
            "2xs": { max: "375px" },
        },
        fontFamily: {
            sans: ["Raleway", "sans-serif"],
        },
        colors: {
            emerald: null,
            indigo: null,
            yellow: null,
            amber: null,
            red: null,
            orange: null,
            lime: null,
            green: null,
            teal: null,
            sky: null,
            cyan: null,
            blue: null,
            violet: null,
            purple: null,
            fuchsia: null,
            pink: null,
            slate: null,
            gray: null,
            zinc: null,
            neutral: null,
            stone: null,
            rose: null,
        },
        extend: {
            colors: {
                transparent: "transparent",
                current: "currentColor",
                bodyBackgroundColor: "#fefefe",
                white: "#ffffff",
                black: "#000000",
                dark: "#43484C",
                text: "#767E86",
                primary: {
                    DEFAULT: "#ff7757",
                    50: "#fff4f1",
                    100: "#ffe7e1",
                    200: "#ffd2c7",
                    300: "#ffb2a0",
                    400: "#ff7757",
                    500: "#f85f3b",
                    600: "#e5431d",
                    700: "#c13514",
                    800: "#a02f14",
                    900: "#842d18",
                    950: "#481307",
                },
                secondary: "#334033",
                red: {
                    400: "#ef4950",
                    500: "#eb1c24",
                    600: "#bc161d",
                },
            },
            opacity: {
                1: "0.01",
                2: "0.02",
                3: "0.03",
                4: "0.04",
                5: "0.05",
                6: "0.06",
                7: "0.07",
                8: "0.08",
                9: "0.09",
                10: "0.10",
                11: "0.11",
                12: "0.12",
                13: "0.13",
                14: "0.14",
                15: "0.15",
                16: "0.16",
                17: "0.17",
                18: "0.18",
                19: "0.19",
                20: "0.20",
                21: "0.21",
                22: "0.22",
                23: "0.23",
                24: "0.24",
                25: "0.25",
                26: "0.26",
                27: "0.27",
                28: "0.28",
                29: "0.29",
                30: "0.30",
                31: "0.31",
                32: "0.32",
                33: "0.33",
                34: "0.34",
                35: "0.35",
                36: "0.36",
                37: "0.37",
                38: "0.38",
                39: "0.39",
                40: "0.40",
                41: "0.41",
                42: "0.42",
                43: "0.43",
                44: "0.44",
                45: "0.45",
                46: "0.46",
                47: "0.47",
                48: "0.48",
                49: "0.49",
                50: "0.50",
                51: "0.51",
                52: "0.52",
                53: "0.53",
                54: "0.54",
                55: "0.55",
                56: "0.56",
                57: "0.57",
                58: "0.58",
                59: "0.59",
                60: "0.60",
                61: "0.61",
                62: "0.62",
                63: "0.63",
                64: "0.64",
                65: "0.65",
                66: "0.66",
                67: "0.67",
                68: "0.68",
                69: "0.69",
                70: "0.70",
                71: "0.71",
                72: "0.72",
                73: "0.73",
                74: "0.74",
                75: "0.75",
                76: "0.76",
                77: "0.77",
                78: "0.78",
                79: "0.79",
                80: "0.80",
                81: "0.81",
                82: "0.82",
                83: "0.83",
                84: "0.84",
                85: "0.85",
                86: "0.86",
                87: "0.87",
                88: "0.88",
                89: "0.89",
                90: "0.90",
                91: "0.91",
                92: "0.92",
                93: "0.93",
                94: "0.94",
                95: "0.95",
                96: "0.96",
                97: "0.97",
                98: "0.98",
                99: "0.99",
                100: "1",
            },
            aspectRatio: {
                auto: "auto",
                square: "1 / 1",
                video: "16 / 9",
                unset: "unset",
            },
            zIndex: {
                2: "2",
                3: "3",
                4: "4",
                5: "5",
                6: "6",
                7: "7",
                8: "8",
                9: "9",
                60: "60",
                70: "70",
                80: "80",
                90: "90",
                100: "100",
                200: "200",
                250: "250",
            },
            transitionDuration: {
                0: "0ms",
                250: "250ms",
                350: "350ms",
                450: "450ms",
                600: "600ms",
                750: "750ms",
                800: "800ms",
                850: "850ms",
                900: "900ms",
                950: "950ms",
                1000: "1000ms",
            },
            backgroundImage: {
                "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
            },
            transitionTimingFunction: {
                courier: "cubic-bezier(.57,.21,.69,1.25)",
            },
            keyframes: {
                reveal: {
                    from: {},
                    to: { transform: "translate(0) skew(0) rotate(0)" },
                },
                revealReverse: {
                    from: { transform: "translate(0) skew(0) rotate(0)" },
                    to: {},
                },
                dash: {
                    from: {
                        strokeDasharray: "100%",
                        strokeDashoffset: "100%",
                    },
                    to: {
                        strokeDasharray: "1000%",
                        strokeDashoffset: "0%",
                    },
                },
            },
            animation: {
                dash: "dash 3s linear infinite alternate",
                reveal: "reveal forwards .5s",
                revealReverse: "revealReverse forwards .5s",
            },
        },
    },
    safelist: [
        "group-[&:not(.active)]/maxH:3xl:!max-h-0",
        "group-[&:not(.active)]/maxH:2xl:!max-h-0",
        "group-[&:not(.active)]/maxH:xl:!max-h-0",
        "group-[&:not(.active)]/maxH:lg:!max-h-0",
        "group-[&:not(.active)]/maxH:md:!max-h-0",
        "group-[&:not(.active)]/maxH:sm:!max-h-0",
        "group-[&:not(.active)]/maxH:xs:!max-h-0",
        "group-[&:not(.active)]/maxH:!max-h-0",
        "group-[&:not(.active)]/maxH:min-3xl:!max-h-0",
        "group-[&:not(.active)]/maxH:min-2xl:!max-h-0",
        "group-[&:not(.active)]/maxH:min-xl:!max-h-0",
        "group-[&:not(.active)]/maxH:min-lg:!max-h-0",
        "group-[&:not(.active)]/maxH:min-md:!max-h-0",
        "group-[&:not(.active)]/maxH:min-sm:!max-h-0",
        "group-[&:not(.active)]/maxH:min-xs:!max-h-0",
    ],
    plugins: [
        plugin(function ({ matchUtilities, theme }) {
            matchUtilities(
                {
                    "translate-z": (value) => ({
                        "--tw-translate-z": value,
                        transform: ` translate3d(var(--tw-translate-x), var(--tw-translate-y), var(--tw-translate-z)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))`,
                    }), // this is actual CSS
                },
                { values: theme("translate"), supportsNegativeValues: true }
            );
        }),
        require("@tailwindcss/container-queries"),
        require("tailwind-scrollbar")({ nocompatible: true }),
    ],
};
